### ISSUE TITLE
play/stop audio

### ISSUE THREAD

**Issue by Hiori555** [PhoenixWyllow/MacroDeck.SoundPad#24]
Soundboard4macrodeck play/stop audio is very useful, it should come here too. I can't use it just because of this.

![Screenshot_11](https://github.com/user-attachments/assets/f900e60c-b8a3-4aca-886d-053c663d0932)

**Comment by PhoenixWyllow** [comment]
This is not planned due to personal time constraints. 
For Soundboard this feature was necessary to avoid complications with variables and tracking active buttons. 
For this plugin, SoundPad allows reproducing only one audio file at a time.
Create a separate button to stop the current track with the stop action. This will work just like playing one audio, then playing another before the first is finished playing.
If you want the same play/stop functionality, you can create a conditional action. Here is an example:
![image](https://github.com/user-attachments/assets/e9e2480f-5127-4a2a-ba15-ab0a6b87d7dd)

There were plans for better management using Macrodeck variables, but I've had no time to work on this further and make a version that I'm happy to release.
